// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCap60BEVk5sHS79MbOWFtVFupdUOWQfsQ',
    appId: '1:355070575193:web:5e272b2a67548ce2c0a748',
    messagingSenderId: '355070575193',
    projectId: 'ucao-examen-a17af',
    authDomain: 'ucao-examen-a17af.firebaseapp.com',
    storageBucket: 'ucao-examen-a17af.firebasestorage.app',
    measurementId: 'G-95C82QKYSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpiXOI-Qq8rfdJCt1SOtMUYkP-mYm5-o',
    appId: '1:355070575193:android:000fdfd61b3a304bc0a748',
    messagingSenderId: '355070575193',
    projectId: 'ucao-examen-a17af',
    storageBucket: 'ucao-examen-a17af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWbeFlM15cDWGL2HJ8FsZbBkdza1XGJI',
    appId: '1:355070575193:ios:3ce51b9e4873b61ec0a748',
    messagingSenderId: '355070575193',
    projectId: 'ucao-examen-a17af',
    storageBucket: 'ucao-examen-a17af.firebasestorage.app',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQWbeFlM15cDWGL2HJ8FsZbBkdza1XGJI',
    appId: '1:355070575193:ios:3ce51b9e4873b61ec0a748',
    messagingSenderId: '355070575193',
    projectId: 'ucao-examen-a17af',
    storageBucket: 'ucao-examen-a17af.firebasestorage.app',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCap60BEVk5sHS79MbOWFtVFupdUOWQfsQ',
    appId: '1:355070575193:web:6d3373e479ef2cb5c0a748',
    messagingSenderId: '355070575193',
    projectId: 'ucao-examen-a17af',
    authDomain: 'ucao-examen-a17af.firebaseapp.com',
    storageBucket: 'ucao-examen-a17af.firebasestorage.app',
    measurementId: 'G-FQ1B6C9VPF',
  );
}
